### ISSUE TITLE
How does your Mouse Event and Is Visible work. Its like magic who calls them

### ISSUE THREAD

**Issue by IAFahim** [kevincastejon/Unity-Missing-Features#1]
My Mind is blown

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaWlodjZyaTZwbTl1ODVxbmtjNzRoN2U0Yzk0aTRob3k0OHNlcHZ3cyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/cFOaorIxCo8Ra/giphy.gif)

**Comment by kevincastejon** [comment]
@IAFahim thanks for your comment. Sorry for delay, I'm in travel right now. The event section of this package is mainly and simply using the "Unity Message methods", which are native Unity callback methods, automatically called by Unity on MonoBehaviour components.

**Comment by IAFahim** [comment]
Thank you so much replying and exapling so nicely, I wish you a have a very safe travels Sir. Your codes are really clean and it helped me a lot to understand unity. Thank you so much. I am really grateful to you.

**Comment by kevincastejon** [comment]
You're welcome 🙏
Just know that this package is now available directly on the official Unity Asset Store here : https://assetstore.unity.com/packages/tools/utilities/missing-features-283473
If you like it, think about writing a review, you would be the first reviewer as it just has been accepted by Unity 😉

**Comment by IAFahim** [comment]
Done. Thank you, thank you, thank you. It was an honor to be the first to write a review.

**Comment by kevincastejon** [comment]
@IAFahim  Just a small update here to notify that the AssetStore package now install itself correctly into the Packages folder instead of installing faulty into the Assets one. You can delete the package folder inside Assets and reinstall via the AssetStore.

**Comment by IAFahim** [comment]
Yeahyy, Thank you Sir
